version: "3"
services:
  ethereum:
    image: ethereum/client-go:latest
    command:
      - "--http"
      - "--http.addr=0.0.0.0"
    ports:
      - 8545:8545
      - 8546:8546
      - 30303:30303
      - 30304:30304
    volumes:
      - ./data:/root/.ethereum/
